chmod ug=wx,o=rx lab0/beautifly3
chmod 400 lab0/beautifly3/lampent
chmod ug-rwx,o=r lab0/beautifly3/nincada
chmod u=r,go-rwx lab0/beautifly3/snubbull
chmod 700 lab0/beautifly3/archeops
chmod 444 lab0/beautifly3/slowking
chmod 404 lab0/beautifly3/pidove
chmod 700 lab0/garchomp1
chmod u=wx,g=rwx,o=rx lab0/garchomp1/porygonz
chmod u=rx,g=x,o=wx lab0/garchomp1/deerling
chmod u=r,go-rwx lab0/garchomp1/sceptile
chmod 064 lab0/goldeen3
chmod u=rw,go=w lab0/magnemite0
chmod u=rx,g=x,o=wx lab0/rattata8	
chmod u=wx,g=rw,o=wx lab0/rattata8/pansear
chmod u=wx,g=rw,o=wx lab0/rattata8/nuzleaf
chmod 444 lab0/rattata8/espeon
chmod 660 lab0/sunkern6
